/*
 Generated by typeshare 1.13.4
*/

export interface AgentsModels {
	agent_id: string;
}

export interface AppLogNavigationBlocked {
	conversation_id: string;
	server_id: string;
	template_ref: string;
	url: string;
}

export interface AppResolveTemplate {
	conversation_id: string;
	server_id: string;
	template_ref: string;
}

export interface AppRespondBridgeConsent {
	conversation_id: string;
	request_id: string;
	option_id: string;
}

export interface AppSubmitBridgeRequest {
	conversation_id: string;
	server_id: string;
	app_id: string;
	template_ref: string;
	request_json: string;
}

export interface ArtifactLogNavigationBlocked {
	conversation_id: string;
	url: string;
}

export interface ArtifactVerifyInline {
	size: number;
	sha256: string;
	inline_content: string;
}

export interface AttachmentContent {
	data_base64: string;
}

export interface AttachmentReadVerified {
	conversation_id: string;
	path: string;
	size: number;
	sha256: string;
}

export interface AttachmentVerifiedPath {
	conversation_id: string;
	path: string;
	size: number;
	sha256: string;
}

export interface RelayEndpoint {
	endpoint: string;
	use_tls: boolean;
}

export interface ConnectionOffer {
	v: number;
	server_id: string;
	daemon_public_key_b64: string;
	relay: RelayEndpoint;
}

export interface ConversationCreate {
	title: string;
	harness_id: string;
	model_id: string;
}

export interface ConversationDelete {
	id: string;
}

export interface ConversationDto {
	id: string;
	title: string;
	active_harness_id?: string;
	model_id?: string;
	forked_from?: string;
	transcript_json: string;
}

export interface ConversationExportBundle {
	conversation_id: string;
	dest_path: string;
}

export interface ConversationFolderPath {
	conversation_id: string;
}

export interface ConversationFork {
	id: string;
	harness_id: string;
	model_id: string;
}

export interface ConversationImport {
	source_path: string;
}

export interface ConversationLoad {
	id: string;
}

export interface ConversationSendMessage {
	conversation_id: string;
	text: string;
}

export interface ConversationSummaryDto {
	id: string;
	title: string;
	updated_at: string;
	active_harness_id?: string;
}

export interface DiagnosticsWriteBundle {
	dest_path: string;
	system_info_json: string;
}

export interface ElicitationRespond {
	conversation_id: string;
	request_id: string;
	action: string;
	data_json?: string;
}

/**
 * Params for a [`method::EVENT`] notification: the daemon-to-client push that
 * replaces the in-process `ConversationObserver` callback. `payload_json`
 * carries the reduced event content exactly as the shell already parses it.
 */
export interface EventNotification {
	conversation_id: string;
	kind: string;
	payload_json: string;
}

/**
 * Capability flags. Additive only. A client checks the flag before using a
 * feature; a `false` (or absent, via `#[serde(default)]`) flag means the daemon
 * does not support it and the client shows an "update the host" affordance
 * rather than degrading.
 * 
 * COMPAT(features): every field added here is gated at the call site with a
 * `// COMPAT(<feature>): added in v<x>` marker so the cleanup list is greppable.
 */
export interface Features {
	/** Daemon exposes the configurable orchestration engine (Workstream C). */
	orchestration?: boolean;
	/**
	 * Daemon can hand native tool catalogs to adapters that accept them
	 * (Workstream B).
	 */
	native_tools?: boolean;
	/**
	 * Daemon can import native harness sessions into vault conversations
	 * (Workstream B).
	 */
	session_import?: boolean;
	/** Daemon can bridge remote clients through the E2E relay (Workstream A). */
	relay?: boolean;
}

export interface GatewayCompleteOauth {
	callback_url: string;
}

export interface GatewayEnvVarDto {
	name: string;
	value: string;
}

export interface GatewayExportCredential {
	credential_ref: string;
}

export interface GatewayServerDto {
	id: string;
	display_name: string;
	enabled: boolean;
	scope: string;
	transport: string;
	stdio_command: string;
	stdio_args: string[];
	stdio_env: GatewayEnvVarDto[];
	http_endpoint: string;
	credential_refs: string[];
	missing_credential_refs: string[];
	oauth_status: string;
	oauth_token_ref: string;
	oauth_client_id: string;
	oauth_authorization_endpoint: string;
	oauth_token_endpoint: string;
	oauth_scopes: string[];
	cap_tools: string;
	cap_resources: string;
	cap_prompts: string;
	cap_elicitation: string;
	cap_apps: string;
	cap_tasks: string;
	cap_roots: string;
	cap_sampling: string;
	connection_status: string;
	last_error: string;
	timeout_secs?: number;
}

export interface GatewaySaveServers {
	servers: GatewayServerDto[];
}

export interface GatewaySetCredential {
	credential_ref: string;
	value: string;
}

export interface GatewaySetDefaultTimeout {
	default_call_timeout_secs: number;
}

export interface GatewayStartOauth {
	server_id: string;
	redirect_uri: string;
}

/**
 * Client kind, advertised in the [`Hello`] handshake. Mirrors paseo's
 * `clientType` so the daemon can reason about who is connected.
 */
export enum ClientType {
	/** The native macOS shell. */
	Desktop = "desktop",
	/** A browser / PWA client. */
	Browser = "browser",
	/** A mobile client (iOS/Android). */
	Mobile = "mobile",
	/** The command-line client. */
	Cli = "cli",
}

/**
 * First frame a client sends after connecting. The daemon replies with
 * [`ServerInfo`].
 */
export interface Hello {
	client_id: string;
	client_type: ClientType;
	protocol_version: string;
	app_version?: string;
}

export interface NativeSessionSummary {
	provider: string;
	path: string;
	title: string;
	updated_at: number;
	session_id?: string;
	cwd?: string;
}

export interface OrchestrationCancel {
	run_id: string;
}

export interface OrchestrationRun {
	recipe_id: string;
	source_conversation_id: string;
	inputs_json?: string;
}

export interface OrchestrationRunDto {
	id: string;
	recipe_id: string;
	source_conversation_id: string;
	status: string;
	current_step: number;
	latest_conversation_id: string;
	branch_conversation_ids?: string[];
	error?: string;
	started_at: string;
	updated_at: string;
}

export interface OrchestrationStatus {
	run_id: string;
}

export interface PermissionRespond {
	conversation_id: string;
	request_id: string;
	option_id: string;
}

export interface RecipeLoadDto {
	recipe_json: string;
}

export interface RecipeSummary {
	id: string;
	title: string;
	description?: string;
}

export interface RecipesLoad {
	recipe_id: string;
}

export interface RootDto {
	id: string;
	name: string;
	uri: string;
	kind: string;
	scope: string;
}

export interface RootsAttach {
	conversation_id: string;
	name: string;
	uri: string;
	kind: string;
	scope: string;
}

export interface RootsList {
	conversation_id: string;
}

export interface RootsRemove {
	conversation_id: string;
	root_id: string;
}

export interface RootsSyncRuntime {
	conversation_id: string;
	roots: RootDto[];
}

export interface RunCancel {
	conversation_id: string;
}

export interface SearchConversations {
	query: string;
}

/** Daemon identity + capabilities, returned in response to [`Hello`]. */
export interface ServerInfo {
	server_id: string;
	version: string;
	protocol_version: string;
	features?: Features;
}

export interface SessionsImport {
	provider: string;
	path: string;
	harness_id: string;
	model_id: string;
}

export interface TaskCancel {
	conversation_id: string;
	task_id: string;
}

export interface UiEvent {
	conversation_id: string;
	kind: string;
	payload_json: string;
}

export interface WorkdirCopyFile {
	conversation_id: string;
	source_path: string;
}

export interface WorkdirWriteFile {
	conversation_id: string;
	filename: string;
	data_base64: string;
}

export interface WorkdirFileContent {
	mime_type?: string;
	data_base64: string;
}

export interface WorkdirListFiles {
	conversation_id: string;
}

export interface WorkdirPath {
	conversation_id: string;
}

export interface WorkdirReadFile {
	conversation_id: string;
	relative_path: string;
}

