/**
 * Shared daemon discovery / ensure helpers for tamtri dev scripts.
 */

import { spawn, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { networkInterfaces } from "node:os";
import { dirname, join } from "node:path";

export function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export function getLanIp() {
  const nets = networkInterfaces();
  for (const entries of Object.values(nets)) {
    for (const net of entries ?? []) {
      if (net.family === "IPv4" && !net.internal) {
        return net.address;
      }
    }
  }
  return null;
}

export function readPublishedEndpoint(tamtriHome) {
  const portFile = join(tamtriHome, "daemon.port");
  const tokenFile = join(tamtriHome, "daemon.token");
  const pidFile = join(tamtriHome, "daemon.pid");
  if (!existsSync(portFile) || !existsSync(tokenFile) || !existsSync(pidFile)) {
    return null;
  }
  const port = Number.parseInt(readFileSync(portFile, "utf8").trim(), 10);
  const token = readFileSync(tokenFile, "utf8").trim();
  const pid = Number.parseInt(readFileSync(pidFile, "utf8").trim(), 10);
  if (!Number.isFinite(port) || port <= 0 || !token || !Number.isFinite(pid)) {
    return null;
  }
  return { port, token, pid };
}

export function isProcessAlive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

export async function probeDaemon(port, token, timeoutMs = 4_000) {
  const wsUrl = `ws://127.0.0.1:${port}/ws?token=${encodeURIComponent(token)}`;
  return new Promise((resolve) => {
    let settled = false;
    const finish = (ok) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      try {
        socket.close();
      } catch {
        /* ignore */
      }
      resolve(ok);
    };

    const socket = new WebSocket(wsUrl);
    const timer = setTimeout(() => finish(false), timeoutMs);
    socket.addEventListener("open", () => finish(true));
    socket.addEventListener("error", () => finish(false));
  });
}

export async function waitForEndpoint(tamtriHome, expectedPid, timeoutMs = 15_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const endpoint = readPublishedEndpoint(tamtriHome);
    if (
      endpoint &&
      endpoint.pid === expectedPid &&
      (await probeDaemon(endpoint.port, endpoint.token, 1_500))
    ) {
      return endpoint;
    }
    await sleep(50);
  }
  throw new Error(
    `daemon (pid ${expectedPid}) did not publish a reachable endpoint in ~/.tamtri within ${timeoutMs}ms`,
  );
}

export function writeAppEnv(appDir, wsUrl, token) {
  const appEnvFile = join(appDir, ".env.development.local");
  const lines = [
    "# Generated by tamtri dev scripts — do not commit",
    `EXPO_PUBLIC_DAEMON_WS_URL=${wsUrl}`,
    `EXPO_PUBLIC_DAEMON_TOKEN=${token}`,
    "",
  ];
  writeFileSync(appEnvFile, lines.join("\n"), "utf8");
  console.log(`Wrote ${appEnvFile}`);
}

export function writeDevEndpoint(appDir, wsUrl, token, { localhostWsUrl } = {}) {
  const devEndpointFile = join(appDir, "public/tamtri-dev-endpoint.json");
  const publicDir = dirname(devEndpointFile);
  if (!existsSync(publicDir)) {
    mkdirSync(publicDir, { recursive: true });
  }
  const payload = { wsUrl, token };
  if (localhostWsUrl) {
    payload.localhostWsUrl = localhostWsUrl;
  }
  writeFileSync(devEndpointFile, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
  console.log(`Wrote ${devEndpointFile}`);
}

/** Rebuild tamtri-daemon when sources are newer than the debug binary. Returns true if a rebuild ran. */
export function ensureDaemonBinary(repoRoot, daemonBin) {
  const sourceMarkers = [
    join(repoRoot, "core/src/daemon/dispatch.rs"),
    join(repoRoot, "core/src/app.rs"),
    join(repoRoot, "daemon/src/main.rs"),
  ];

  if (!existsSync(daemonBin)) {
    console.log("Building tamtri-daemon (binary missing)…");
  } else {
    const binMtime = statSync(daemonBin).mtimeMs;
    const stale = sourceMarkers.some(
      (path) => existsSync(path) && statSync(path).mtimeMs > binMtime,
    );
    if (!stale) return false;
    console.log("Rebuilding tamtri-daemon (Rust sources changed since last build)…");
  }

  const result = spawnSync("cargo", ["build", "-p", "tamtri-daemon"], {
    cwd: repoRoot,
    stdio: "inherit",
  });
  if (result.status !== 0) {
    console.error("cargo build -p tamtri-daemon failed");
    process.exit(result.status ?? 1);
  }
  return true;
}

/**
 * Ensure a reachable tamtri-daemon, reusing ~/.tamtri when possible.
 * @returns {{ endpoint: { port, token, pid }, child: import('node:child_process').ChildProcess | null, spawned: boolean }}
 */
export async function ensureDaemon({
  repoRoot,
  tamtriHome,
  requestedPort = "8377",
  daemonBin,
  bindHost = "127.0.0.1",
}) {
  const rebuilt =
    repoRoot != null ? ensureDaemonBinary(repoRoot, daemonBin) : !existsSync(daemonBin);

  if (rebuilt && repoRoot == null) {
    console.error(`tamtri-daemon not found at ${daemonBin}`);
    console.error("Run: pnpm run daemon:build");
    process.exit(1);
  }

  const existing = readPublishedEndpoint(tamtriHome);
  if (!rebuilt && existing && isProcessAlive(existing.pid)) {
    const reachable = await probeDaemon(existing.port, existing.token);
    if (reachable) {
      console.log(`Reusing tamtri-daemon (pid ${existing.pid}) on port ${existing.port}`);
      return { endpoint: existing, child: null, spawned: false };
    }
    console.warn(
      `Daemon pid ${existing.pid} is alive but WebSocket probe failed; starting a fresh daemon…`,
    );
  } else if (rebuilt && existing && isProcessAlive(existing.pid)) {
    console.log(`Stopping stale tamtri-daemon (pid ${existing.pid}) after rebuild…`);
    try {
      process.kill(existing.pid, "SIGTERM");
    } catch {
      /* ignore */
    }
    await sleep(500);
  } else if (existing) {
    console.log("Daemon endpoint files exist but the process is not running; starting tamtri-daemon…");
  } else {
    console.log("No daemon endpoint in ~/.tamtri; starting tamtri-daemon…");
  }

  if (!existsSync(daemonBin)) {
    console.error(`tamtri-daemon not found at ${daemonBin}`);
    console.error("Run: pnpm run daemon:build");
    process.exit(1);
  }

  const child = spawn(daemonBin, [], {
    env: {
      ...process.env,
      TAMTRI_HOME: tamtriHome,
      TAMTRI_PORT: requestedPort,
      TAMTRI_BIND: bindHost,
    },
    stdio: "ignore",
  });

  if (child.pid == null) {
    throw new Error("failed to spawn tamtri-daemon");
  }

  const endpoint = await waitForEndpoint(tamtriHome, child.pid);
  console.log(`Started tamtri-daemon (pid ${endpoint.pid}) on port ${endpoint.port}`);
  return { endpoint, child, spawned: true };
}
