//! Declarative orchestration recipes stored in the legible vault.
//!
//! Recipes are prompt-free run graphs: the engine sequences harness runs and
//! branches on structured signals. Message text lives in the recipe file (user
//! authored) or in caller-supplied inputs, never generated by the engine.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use typeshare::typeshare;

pub const RECIPE_SCHEMA_VERSION: u32 = 1;

#[typeshare]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RecipeSummary {
    pub id: String,
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Recipe {
    pub schema_version: u32,
    pub id: String,
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub steps: Vec<RecipeStep>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RecipeStep {
    /// Fork the source conversation, send one message, wait for the turn to end.
    ForkRun {
        harness_id: String,
        model_id: String,
        message: String,
    },
    /// Fan out the same briefing to multiple harnesses in parallel (committee).
    Parallel {
        branches: Vec<ParallelBranch>,
    },
    /// Repeat a fork/run cycle up to `max_iterations` times on the latest fork.
    Loop {
        max_iterations: u32,
        harness_id: String,
        model_id: String,
        message: String,
    },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ParallelBranch {
    pub harness_id: String,
    pub model_id: String,
    pub message: String,
}

impl Recipe {
    pub fn validate(&self) -> Result<(), String> {
        if self.schema_version != RECIPE_SCHEMA_VERSION {
            return Err(format!(
                "unsupported recipe schema version {}",
                self.schema_version
            ));
        }
        if self.id.trim().is_empty() {
            return Err("recipe id is required".to_string());
        }
        if self.steps.is_empty() {
            return Err("recipe must contain at least one step".to_string());
        }
        for step in &self.steps {
            step.validate()?;
        }
        Ok(())
    }

    pub fn summary(&self) -> RecipeSummary {
        RecipeSummary {
            id: self.id.clone(),
            title: self.title.clone(),
            description: self.description.clone(),
        }
    }
}

impl RecipeStep {
    fn validate(&self) -> Result<(), String> {
        match self {
            RecipeStep::ForkRun {
                harness_id,
                model_id,
                message,
            } => {
                require_non_empty(harness_id, "harness_id")?;
                require_non_empty(model_id, "model_id")?;
                require_non_empty(message, "message")?;
            }
            RecipeStep::Parallel { branches } => {
                if branches.is_empty() {
                    return Err("parallel step needs at least one branch".to_string());
                }
                for branch in branches {
                    require_non_empty(&branch.harness_id, "harness_id")?;
                    require_non_empty(&branch.model_id, "model_id")?;
                    require_non_empty(&branch.message, "message")?;
                }
            }
            RecipeStep::Loop {
                max_iterations,
                harness_id,
                model_id,
                message,
            } => {
                if *max_iterations == 0 {
                    return Err("loop max_iterations must be > 0".to_string());
                }
                require_non_empty(harness_id, "harness_id")?;
                require_non_empty(model_id, "model_id")?;
                require_non_empty(message, "message")?;
            }
        }
        Ok(())
    }
}

fn require_non_empty(value: &str, field: &str) -> Result<(), String> {
    if value.trim().is_empty() {
        return Err(format!("{field} is required"));
    }
    Ok(())
}

/// Replace `{{key}}` placeholders using the supplied input map.
pub fn apply_template(template: &str, inputs: &HashMap<String, String>) -> String {
    let mut out = template.to_string();
    for (key, value) in inputs {
        out = out.replace(&format!("{{{{{key}}}}}"), value);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_substitution_replaces_known_keys() {
        let mut inputs = HashMap::new();
        inputs.insert("message".to_string(), "Analyze the CSV".to_string());
        assert_eq!(
            apply_template("Please {{message}} now.", &inputs),
            "Please Analyze the CSV now."
        );
    }

    #[test]
    fn recipe_validation_rejects_empty_steps() {
        let recipe = Recipe {
            schema_version: RECIPE_SCHEMA_VERSION,
            id: "empty".to_string(),
            title: "Empty".to_string(),
            description: None,
            steps: vec![],
        };
        assert!(recipe.validate().is_err());
    }
}
